// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: api_get_user_authority.proto

package backend_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ユーザ権限取得API リクエスト
type GetUserAuthorityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetUserAuthorityRequest) Reset() {
	*x = GetUserAuthorityRequest{}
	mi := &file_api_get_user_authority_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthorityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthorityRequest) ProtoMessage() {}

func (x *GetUserAuthorityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_get_user_authority_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthorityRequest.ProtoReflect.Descriptor instead.
func (*GetUserAuthorityRequest) Descriptor() ([]byte, []int) {
	return file_api_get_user_authority_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserAuthorityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ユーザ権限取得API レスポンス
type GetUserAuthorityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserDetail []*UserAuthority `protobuf:"bytes,1,rep,name=userDetail,proto3" json:"userDetail,omitempty"`
}

func (x *GetUserAuthorityResponse) Reset() {
	*x = GetUserAuthorityResponse{}
	mi := &file_api_get_user_authority_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthorityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthorityResponse) ProtoMessage() {}

func (x *GetUserAuthorityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_get_user_authority_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthorityResponse.ProtoReflect.Descriptor instead.
func (*GetUserAuthorityResponse) Descriptor() ([]byte, []int) {
	return file_api_get_user_authority_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserAuthorityResponse) GetUserDetail() []*UserAuthority {
	if x != nil {
		return x.UserDetail
	}
	return nil
}

var File_api_get_user_authority_proto protoreflect.FileDescriptor

var file_api_get_user_authority_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4a,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x75, 0x73,
	0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x52, 0x0a,
	0x75, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x77, 0x6f, 0x61, 0x2f, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_get_user_authority_proto_rawDescOnce sync.Once
	file_api_get_user_authority_proto_rawDescData = file_api_get_user_authority_proto_rawDesc
)

func file_api_get_user_authority_proto_rawDescGZIP() []byte {
	file_api_get_user_authority_proto_rawDescOnce.Do(func() {
		file_api_get_user_authority_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_get_user_authority_proto_rawDescData)
	})
	return file_api_get_user_authority_proto_rawDescData
}

var file_api_get_user_authority_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_get_user_authority_proto_goTypes = []any{
	(*GetUserAuthorityRequest)(nil),  // 0: GetUserAuthorityRequest
	(*GetUserAuthorityResponse)(nil), // 1: GetUserAuthorityResponse
	(*UserAuthority)(nil),            // 2: UserAuthority
}
var file_api_get_user_authority_proto_depIdxs = []int32{
	2, // 0: GetUserAuthorityResponse.userDetail:type_name -> UserAuthority
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_get_user_authority_proto_init() }
func file_api_get_user_authority_proto_init() {
	if File_api_get_user_authority_proto != nil {
		return
	}
	file_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_get_user_authority_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_get_user_authority_proto_goTypes,
		DependencyIndexes: file_api_get_user_authority_proto_depIdxs,
		MessageInfos:      file_api_get_user_authority_proto_msgTypes,
	}.Build()
	File_api_get_user_authority_proto = out.File
	file_api_get_user_authority_proto_rawDesc = nil
	file_api_get_user_authority_proto_goTypes = nil
	file_api_get_user_authority_proto_depIdxs = nil
}
